### ISSUE TITLE
[BUG]  Unbound Context Crash

### ISSUE THREAD

**Issue by conneich** [ChaoticTrials/VanillaAIOTs#3]
### Minecraft version

1.18.2

### Vanilla AIOTs version

1.1.2

### Forge version

40.1.68

### The latest.log file

https://pastebin.com/dh67b90K

### Issue description

Right-clicking with a Stone AIOT causes a crash.

### Steps to reproduce

Right-click dirt.

**Comment by MelanX** [comment]
Already fixed in 1.1.3 (see #2)
